# (PART) What is science? {.unnumbered}

# Science

Academic research is all about generating knowledge: knowledge about how the world works, and how humans operate within it. This knowledge can be desirable for its practical implications --- building aircraft, developing better educational policies, curing diseases --- but it can also be desirable for its own sake, satisfying our intrinsic human curiosity for understanding our environment.

There are many ways of generating knowledge. We might develop important insights into a historical phenomenon by reading appropriate source material and thinking about how it all fits together. We might learn about educational inequality by analysing demographic data and exam results for students around the country. We might learn about role of religion in indigenous societies by living with these societies and interviewing their members. Different kinds of knowledge demand different kinds of approaches, and there's no one-size-fits-all solution that covers everything.

Scientific research corresponds to a particular approach to knowledge generation. This approach is characterised by sets of ideals about (a) what theories should look like, (b) what evidence should look like, and (c) what methods should be used to collect this evidence.

## Theories

A scientific theory is a statement about how something works. This could mean all kinds of things: the way stars move through the sky, the way ants communicate with one another, or the way continents were formed.

Four criteria are held to be particularly important for scientific theories: *generality*, *predictivity*, *simplicity*, and *reductivity*.

**Generality.** A theory is *general* if it applies in a broad range of contexts and explains a broad range of phenomena. Scientists value general theories because they tend to identify more fundamental aspects of nature, as well as having more widespread practical applications. For example, a scientist would be more interested in developing a general theory of melodic patterns in baroque music than developing a theory of melodic patterns in a specific sonata by Bach.

**Predictivity.** A theory is *predictive* if it accurately predicts observed data. This predictivity is particularly valuable in situations where other theories fail to predict the same data. Predictivity is valued because it suggests that the theory provides an accurate model of the world, and because predictive theories are useful for real-world decision-making (e.g. how to combat inflation, how to improve educational attainment in inner cities, how to counteract global heating). A prerequisite for a theory to be predictive is for it to be *testable*, which means generating predictions that can one day be evaluated against scientific observations. Scientists have little time for untestable theories because they have no chance of satisfying the predictivity criterion.

**Testability.** A theory is *testable* if it generates predictions that one could reasonably test with scientific measurement. For example, if I had a theory that music sounds better after drinking coffee, I could test this theory by having people listen to various musical pieces before and after drinking coffee, and ask them how good the music sounded. In contrast, a theory that music written before 1900 is better than music written after 1900 is fundamentally untestable, because there is no accepted way to measure how 'good' a piece of music is.

**Simplicity.** Scientists value simple theories over complex theories, a principle which is often termed *Occam's razor*. This principle has practical advantages: it makes theories easier to reason about, easier to test, and easier to communicate to others. There are also some deep mathematical reasons why one should, all else aside, prefer simpler theories (e.g. Chapter 28 of [@MacKay2003-ki]). The clinching motivation for Occam's razor, though, is simply that it seems to work very well in practice. One famous example is when the mathematician and astronomer Nicolaus Copernicus (1473-1543) proposed his *heliocentric* model which placed the Sun at the centre of the universe, as opposed to Ptolemy's *geocentric* model which placed the Earth at the centre of the universe. Copernicus's new model was no better at predicting the movements of celestial bodies than contemporary geocentric models, but it was much simpler, and hence favoured by Occam's razor. Ultimately, of course, Copernicus's model proved to be a much more accurate description of the universe (or at least of our solar system!).

![**Inner planets of the solar system.** Credit: [Datumizer](https://commons.wikimedia.org/wiki/File:Solar_system_orrery_inner_planets.gif), [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0), via Wikimedia Commons](images/solar-system-inner-planets.gif "The inner planets of the solar system"){width="100%"}

**Reductivity.** Scientists believe that all natural phenomena can ultimately be explained by breaking them down into their constituent parts. For example, the social dynamics studied by sociologists will reflect psychological aspects of the individuals in the social group; these psychological aspects have their basis in the behaviour of individual neurons within the brain; the behaviour of these neurons is driven by chemical reactions; these chemical reactions are a consequence of the basic physics of atoms and molecules. Scientific theories must fit coherently within this reductionist framework.

![Credit: [XKCD](https://xkcd.com/435), [CC BY-NC 2.5](https://creativecommons.org/licenses/by-nc/2.5/)](images/xkcd-purity.png){width="100%"}

## Evidence

Scientists rely on evidence for formulating and evaluating their theories. Three criteria are particularly valued for scientific evidence: *objectivity*, *replicability*, and *theoretical impact*.

**Objectivity.** A piece of evidence is *objective* if it is independent of the subjective biases of the researcher. Conversely, a piece of evidence is *subjective* if it depends substantially on a researcher's personal judgements, feelings or experiences. For example, if I wanted to talk about changes in chord progressions through the history of jazz harmony, it would not be very objective to say "I listened to a lot of jazz music over the weekend, and I noticed that older jazz tends to use perfect-fourth root progressions much more than recent jazz". It would be much more objective to say "I used a computer to count root progressions in a dataset of 1,000 jazz standards, and I found a statistically reliable decrease in perfect-fourth root progressions over time" (see [@Broze2013-hm] for such an analysis).

**Replicability.** A piece of evidence is *replicable* if it can be recreated by other researchers using analogous methods. If a piece of evidence proves not to be replicable this suggests that the original result may have been a statistical fluke, or that the initial methods were flawed in an unexpected way. In either case, non-replicable results are poor building blocks for scientific theories.

![Credit: [XKCD](https://xkcd.com/242), [CC BY-NC 2.5](https://creativecommons.org/licenses/by-nc/2.5/)](images/xkcd-replication.png){width="75%"}

**Theoretical impact.** A piece of evidence has high theoretical impact to the extent that it helps (a) to distinguish between competing scientific theories, or (b) to generate new scientific theories. One exciting case is where the research community has a built a strong consensus around a particular theory, but then a new piece of evidence demonstrates that the theory is fundamentally flawed. An alternative exciting case is when a new theory makes a special and unexpected prediction that is subsequently confirmed by a new piece of evidence. One such example is when Albert Einstein predicted the existence of *gravitational waves* -- ripples in spacetime -- on the basis of his general theory of relativity [@Einstein1918-iw].

## Methodology

**Measurement.** Scientific evidence comes primarily from *measurement*. To measure something means to perform an observation according to a standardised procedure that returns a basic piece of data such as a number (e.g. 4.7), a collection of numbers (e.g. [4.7, 2.2, 1.5]), or a category (e.g. 'red'). The purpose of this standardisation is to maximise objectivity, by minimising the subjective role of the experimenter who constructs the results.

**Quantitative analysis.** Science relies heavily on *quantitative* analysis techniques. These are analysis techniques that take basic pieces of data (e.g. numbers, categories), and return summaries of this data, ranging from basic descriptive statistics (e.g. "the mean observed value was 5.4") to advanced relational statistics (e.g. "the estimated causal effect of *X* on *Y* is 4.2"). Importantly, these analysis techniques are designed to be *objective*, in that they minimise the subjective role of the experimenter who interprets the results. Instead of relying on intuitions gleaned from examining the data 'manually', these methods rely on mathematical theories of probability and statistics, providing standardised analysis procedures that could be followed by any quantitative researcher.[^theory-intro-1]

[^theory-intro-1]: In practice, it ends up being rather difficult to eliminate subjective decisions entirely from data analysis. Quantitative analyses do require the researcher to make various decision calls along the way -- what analysis method to apply, what outliers to exclude, what variables to analyse, and whether to transform these variables -- and these decision calls can have material impacts on the final results. The term *p-hacking* is used to describe situations where a researcher (knowingly or unknowingly) exploits this flexibility to find an analysis strategy that preferentially supports their own viewpoint. Several initiatives have become important in recent years for combating this problem, for example *open data* (sharing raw data underlying the analyses), *preregistration* (publicly committing to a particular analysis plan before collecting the data), and *multiverse analysis* (studying the sensitivity of the research's conclusions to different combinations of analysis decisions).

# Science and music

Most students studying music at school or at university will have experienced music primarily as an arts or humanities subject. Such a course might have analytic components, where the student identifies particular structures or patterns within certain pieces of music. It might have historic components, where the student might write about how music reflects contemporaneous trends in politics, literature, and art. It might have practical components, where the student might produce compositions according to given specifications, perform certain musical pieces, or have their listening skills evaluated.

However, it is also perfectly possible to study music from a scientific perspective. Such an approach has some particularly interesting advantages that complement the traditional approach well. Let's consider a few now.

**Reductivity and deeper levels of explanation.** The reductive nature of science gives us a very different perspective on how music works, digging deep below our intuitive understanding of music, and establishing music's foundation in physics, biology, neuroscience, and cognition. These deeper explanatory levels are interesting because they can provide the ultimate explanations for musical truths that we might take for granted (e.g. the consonance of the major third), and can relate music to broader aspects of human evolution and behaviour, for such as language, dance, auditory perception, learning, and social bonding.

**Reductivity and engineering.** If science is about breaking down natural phenomena into their constituent elements, then engineering is about putting these elements together into new technologies. The scientific study of music thereby facilitates a broad range of exciting engineering applications that have deep implications for the way that we engage with and experience music. Over the last two centuries recording technologies already transformed the way in which people experience music in day-to-day life, taking it out of concert halls and religious spaces and into people's homes, cars, and workplaces. Over the last few decades, electronic synthesisers made it possible for individuals to explore and manipulate vast soundworlds with only a limited amount of specialist equipment. In the last few years, advances in machine learning and artificial intelligence have opened up a wide range of game-changing technologies, for example automatic song recognition (see [Shazam](https://www.shazam.com/gb)) and automatic harmonic transcription (see [Chordify](https://chordify.net/)).

**Objectivity and questioning assumptions.** Almost everyone who studies music comes with their own prior experience and intuitions about music. This experience and intuition can be very valuable for contextualising one's music studies, but it also provides a dangerous route for certain assumptions or biases to creep uninterrogated into one's work. Objective methods, if used correctly, can be a good way of addressing such assumptions and biases, because the researcher is forced to support claims with data rather than with intuition.[^theory-intro-2]

[^theory-intro-2]: Of course, it is very possible for so-called objective methods to hide their own assumptions and biases. One common example is *sampling bias*, describing how researchers sample (for example) participants for a psychology experiment, or compositions for a corpus analysis. It is easy for bias to slip into such sampling processes, for example when a psychologist samples their participants solely from a cohort of undergraduate students, and thereby produces conclusions that are biased towards how cognition works in educated, Westernised, high-income individuals.

**Objectivity and scalability.** Objective methods by definition involve a high degree of automation. Automated methods are by nature easier to scale to large datasets. This makes scientific methods good for studying musical phenomena at much larger scales than are tractable using subjective or 'manual' approaches. For example, while a traditional music analyst might ordinarily analyse a single movement of a Mozart piano sonata at a time, we might instead use computer-assisted techniques to analyse the full collection of Mozart piano sonatas at once.

**Psychology and the average listener.** Traditional musicology relies heavily on the insights of expert music scholars, who write about things that they hear in the music or see in the written score. This focus on experts is partly motivated by the fact that traditional musicology places high value on the insights of the expert, but also by the fact that experts have strong technical vocabularies that make it easy for them to describe their musical experiences. More recently, though, the application of psychological methods has allowed researchers to probe the listening experiences of more 'average' listeners in a manner that is relatively unmediated by technical vocabulary (e.g. [@Bigand2006-ik]). This approach is valuable for refocusing musicology away from specialist populations of highly educated listeners and towards the understudied majority of listeners who gain significant pleasure from music without necessarily having any formal musical training.

**Psychology and composition.** Scientific studies provide a compelling way to rationalise various aspects of musical style (e.g. melodic patterns, voice-leading rules, harmonic consonance) in terms of basic principles of acoustics and auditory perception (e.g. [@Harrison2020-gx; @Huron2001-or; @Von_Hippel2000-yo]). The same logic can furthermore be applied to suggest stylistic directions that exploit acoustics and auditory perception in powerful new ways. One interesting example of this is the paradigm of *dynamic tonality*, which builds on original scientific work by William Sethares analysing interactions between timbre and consonance [@Sethares2005-ko]. Dynamic tonality uses computational models of consonance to derive optimal timbres for different musical tuning systems, allowing composers to explore the vast universe of microtonal tuning systems while avoiding the pervasive dissonances that often put listeners off such music (see for example [this demo](https://www.youtube.com/watch?v=Nd4h8vmEsQM)).

**Science and skill development.** Student science projects provide an excellent way to develop generalisable skills that have diverse applications inside and outside of academia. Almost every science project has a significant data analysis component, and data analysis skills are highly valued in almost all industries. Many science projects also provide opportunities to develop programming skills, which are highly valued in many aspects of the technical sector, ranging from web programming to app development to video game design.

## Varieties of musical science

One of the exciting things about musical science research is its great diversity. The field contains many different sub-fields, distinguished in terms of their research questions, philosophies, and research methods. A consequence of this diversity is that the field really does provide something for everyone. Throughout this course, I want you to think with an open mind about the different ways that one can approach music and science: try and identify the research questions that you find interesting, the methods that you find compelling, and the philosophies that resonate most with you.

At the highest level, we can organise the disciplines of musical science research into three broad categories: psychology, music theory, and engineering. In music psychology, the goal is simply to better understand the human mind. In music theory, the goal is to better understand the mechanics of musical style, with less of an emphasis on how the music is actually perceived by the listener. In music engineering, meanwhile, the goal is to create new technologies that help us to perform certain musical tasks, for example recommending new music, transcribing audio recordings, or improving a room's acoustics. Of course, in practice, these categories often overlap and inform each other.

### Music psychology

**Psychoacoustics.** Psychoacoustics corresponds to the interface between physics and psychology. The goal of psychoacoustics is to understand how physical properties of sound, in particular the vibration patterns of air molecules, are translated into psychological percepts such as loudness, pitch, and timbre. Psychoacoustics research typically involves carefully controlled laboratory experiments, where participants have to listen very carefully and describe subtle changes in stimuli.

**Neuroscience.** Music neuroscience research tries to understand how the basic biological structures of the brain support the perception and production of music. A common goal in this research is to localise particular functions to particular brain locations, for example identifying what part of the brain is responsible for pitch perception and what part is responsible for timbre perception. Music neuroscientists mostly conduct their experiments using neuroimaging machines, which allow the researcher to measure certain brain signals associated with certain musical behaviours or thoughts.

**Cognitive science.** Cognitive science sits at a level of abstraction somewhat above neuroscience. Music cognition researchers are less interested than neuroscientists in understanding the biology of the brain; instead, they are more interested in understanding the fundamental computational processes that the brain enacts. The basic principle of cognitive science is that you only really understand a mental process when you can write a computer program that does the same thing. Cognitive science is therefore closely linked with the field of artificial intelligence.

**Evolutionary psychology.** Evolutionary music psychologists are interested in understanding how humankind evolved its capacity for music. On the face of it, music seems to be an evolutionary mystery, because it doesn't have obvious survival or reproductive functions; however, on closer inspection, we can see how it is connected to many fundamental human capacities such as language, emotion, and auditory scene analysis. Evolutionary music psychology can involve excitng field trips, for example studying the acoustics of caves with ancient paintings, or studying prehistoric musical instruments from archaeological excavations.

**Performance studies.** In performance studies, the researcher aims to characterise the nuances of musical performing in a quantitative way. Often this process begins by taking a collection of musical recordings, encoding them digitally, and then analysing the aspects of the performances that were not dictated by the musical score: for example, timing, dynamics, timbre, and articulation. The hope is that this research can give us new insights into what makes a given performer special, and help us to understand the relationship between particular musical techniques (e.g. rubato) and the effect that they have on the listener.

**Musical development.** In musical development research, the goal is to understand the process in which musical abilities develop from birth to adulthood. This research is very useful for understanding what kinds of faculties are innate to the individual, and which only develop through learning and experience. As one might expect, research in this area typically involves lots of behavioural studies with young children; special expertise is required to design experiments that work with these populations, especially as one moves to younger and younger children.

**Music education.** Music education research provides a more applied 'spin' on musical development research. Instead of passively observing musical skills at different ages, the primary goal is rather to develop new teaching methods or improved policies that better support children's musical education. Theoretical work and laboratory experiments do play some role in this research, but ultimately the most important experiments are large-scale observational studies or randomised controlled trials that explore the effects of some intervention on student outcomes.

**Wellbeing and music therapy.** Wellbeing and music therapy research are occupied with understanding how music can help people's quality of life, and designing effective strategies for realising this potential. Music therapy is a long-established and well-regarded occupation, where therapists have face-to-face sessions with patients typically with the goal of using music to overcome verbal communication difficulties. Music therapy research is then typically guided either at developing better therapeutic practices, or at validating the positive effects of music therapy to the wider medical community. Music wellbeing research then takes a somewhat wider perspective, studying musical wellbeing not just in the context of music therapy but also in the context of personal care and other social contexts.

**Cross-cultural research.** Cross-cultural research into music and science has been experiencing a recent resurgence in popularity. Here the goal is to see how music manifests across different parts of the world and in different human societies. This kind of work is important for diversifying our understanding of music. It's also very useful for investigating which aspects of musicality are biologically mandated and which are culturally dependent. This cross-cultural research can include both music psychology, where researchers get participants from different cultures to take part in experiments, but it can also include music theory, where researchers analyse the music of these different cultures.

**Cross-species research.** In cross-species research, scientists try to understand to what extent we share musical capacities with other species in the animal kingdom. Work like this can help us to understand the evolutionary timeline for these different musical capacities, potentially also shedding light on the evolutionary reasons why these different capacities evolved.

**Music and advertising.** Music and advertising is a specifically applied sub-field within music psychology. Here the goal is to improve our understanding of how music can be used to sell a product, for example by understanding its emotional effects on the person watching the advertisement, or by finding good techniques for finding the best musical extract to represent a brand's identity.

### Music theory 

**Corpus studies.** The main intersection of music and science with music theory comes in the form of corpus studies. In corpus studies, the goal is typically to analyse a particular musical style or musical composer. Hundreds or thousands of music compositions are encoded digitally, and the researcher writes computer software that analyses the statistical properties of these compositions, or detects certain patterns in them. This approach provides a way to scale up traditional methods of music analysis to answer interesting questions in a very systematic way. 

**Music and copyright.** Copyright science is a small but interesting sub-field that combines both music theory and music psychology. Here the goal is to develop effective ways to detect and quantify plagiarism in a musical context. Legal challenges concerning music copyright have traditionally relied on manual musical analyses, which brings a certain amount of undesirable subjectivity. There is a hope that computational methods might manage to make this process more objective, and reduce the sense in which court cases depend on the quality of the lawyers involved.

### Music engineering

**Audio engineering.** Audio engineering is focused on problems concerning recording and playing audio. Audio engineers are responsible for developing better microphones and recording equipment, as well as for developing new computational methods for postprocessing audio, for example to separate different instruments into different audio tracks. They are also responsible for developing better speaker systems. There have been some very interesting advances in recent years, for example developing technology to enable a single panel of sound speakers to project a three-dimensional sound environment that audience members can walk around.

**Architectural acoustics.** Architectural acoustics concerns the challenge of building rooms or halls with good acoustic properties. This is obviously important in the musical contexts of concert halls and opera houses, but it's also important in public environments such as supermarkets and railways stations, where it's important to be able to communicate with members of the public via public announcement systems. There is a lot of interesting physics and material science involved in this work.

**Digital musical instruments.** Digital musical instruments have become increasingly important throughout the 20th century. Music psychology plays an important role in this field, helping to understand what aspects of the listener experience should be manipulated, and helping provide design principles to make the instruments intuitive for performers. Music theory plays an useful role, because ultimately the instrument is there for playing music, and music theory helps us to understand the kinds of music that the performer might want to play. Lastly, high-quality engineering is essential for realising the concept as a reliable instrument that performers can use.

**Computer-assisted composition.** Finally, computer-assisted composition is an interesting topic of research that has been steadily growing since its beginnings in the 1950s. In its extreme case, this involves designing autonomous computer software that generates musical compositions by itself. However, an effective middle-ground is to develop software that facilitates rather than replacing the human composition process, for example by generating new melodic or rhythmic ideas for the composer to explore, by providing plausible 'auto-complete' options, or by automatically harmonising melodies. One such example from recent years is Google's '[Magenta](https://magenta.tensorflow.org/)' program, which developed many different computational tools with the goal of stimulating many musicians into exploring computer-assisted composition.
