# Music across the world

```{r, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, results = "asis"
)
source("setup.R")
```

<!-- How to define music? From Savage et al. (2015): -->

<!-- " It should be noted that the editors of the Encyclopedia did not adopt a formal definition of music in choosing their selections. We thus assume that they followed the common practice in ethnomusicology of defining music as “humanly organized sound” (48) other than speech, with the distinction between speech and music being left to each culture’s emic (insider, subjective) conceptions, rather than being defined objectively by outsiders. Thus, our analyses suggest that there is no absolutely universal and objective definition of music, but that Lomax and Grauer’s definition may offer a useful working def- inition to distinguish music from speech." -->

It has long been understood that music can be found in diverse cultures across the world. A recent ethnographic survey of 315 societies across the world found music to be present in every case [@Mehr2019-wg]. This widespread prevalence of music speaks already to its notional evolutionary function: if music is indeed an indispensable part of human society, this suggests that it has some important utility across human cultures that may have a long evolutionary history.

An important question then arises: how does this music-making vary across the world? One way of studying this question is to 'zoom in' on individual societies and study them using *ethnomusicological* methods. Traditionally an ethnomusicologist will spend years embedding themselves within a given musical culture to learn about it as an insider, paying attention both to the structural features of the music and the cultural and social roles it plays within the society. The result is typically a highly detailed understanding of a particular musical culture, developed primarily 'on its own terms', without necessarily referring to other musical cultures around the world.

An alternative approach that has ebbed and flowed in popularity over the decades is *comparative musicology*. Comparative musicology seeks to establish a *comparative* understanding of different musical cultures, looking both at the sense in which they are similar and the sense in which they are different. It is a more scientifically oriented approach, in that it seeks to represent musical pieces and cultures as data points that can be compared quantitatively to one another.

Comparative musicology saw initial popularity from the late 1800s, with researchers such as Erich von Hornbostel (1877-1935). Relevant studies included investigations of scale systems and instrument usage across the world. Unfortunately, this early work ended up manifesting certain characteristics which are generally disapproved of today, for example an 'evolutionist' way of thinking that considered Western art music to be the ultimate end-goal of musical style development, and that considered other musical styles to be 'primitive' in various ways. These philosophical and interpretative issues are part of the reason why ethnomusicology approaches largely displaced comparative musicology for most of the 20th century.

Recent years have seen something of a resurgence of interest in the comparative musicology approach. @Brown2013-lz present a strong argument for setting cross-cultural comparisons at the heart of musicology and music psychology, placing particular emphasis on the desirability of studying *musical universals*, features of music which reliably occur across many musical cultures. @Savage2015-rp present a systematic quantitative analysis of the occurrence of different musical features across a set of globally sampled music recordings. @Mehr2019-wg present a systematic quantitative analysis of ethnographic accounts of music performance from all over the world, focusing in particular on the social contexts in which music manifests in these cultures. Psychological studies have investigated the cross-cultural perception of diverse musical dimensions including pitch [@Jacoby2019-ew], consonance [@McDermott2016-sf], and rhythm [@Jacoby2021-xp]. Together, this work is giving us an increasingly complete picture of the diverse ways in which music manifests across the world, allowing us to explore interesting questions about the genetic and cultural processes underlying music's evolution.

## Structural features of music

Music researchers have written for many decades about cross-cultural differences in musical styles, and have theorised in particular about the idea of *musical universals*, musical features which might reliably occur across many musical cultures. However, little progress was made on this question in the 20th century, with ethnomusicologists tending to avoid this topic and the baggage it brought from traditional comparative musicology. In this section we will discuss a couple of recent articles that revisit this question of musical universals, bringing a quantitative perspective that simultaneously compares many cultures across the world.

### Savage et al. (2015)

@Savage2015-rp analyses a collection of 304 recordings from the *Garland Encyclopedia of World Music*, a dataset comprising recordings from a variety of sources from all over the world, including both field recordings of traditional indigenous music and studio recordings of nontraditional music. The researchers listened to each recording and coded them in terms of 32 musical features covering various aspects of pitch, rhythm, form, instrumentation, performance style, and social context. These features are strongly inspired by the arguments of @Brown2013-lz.

When examining the recurrence of particular features across different cultures, it's important to account for the notion of cultural relatedness. If we see the same musical feature recur many times in cultures that are completely unrelated to each other, this implies that there is some kind of latent evolutionary pressure that encourages the development of that feature. However, if the same musical feature recurs many times in cultures that are close neighbours, the evidence for a latent evolutionary pressure is weaker: it could simply be that the feature developed once by chance in a historical parent culture, and the child cultures just inherited it. @Savage2015-rp therefore use so-called *phylogenetic comparative methods* to adjust for cultural relatedness in their analyses. Their primary analyses operationalise cultural relatedness using data on the historical relatedness of different languages (*language phylogenies*), but they also present supplementary analyses that instead operationalise cultural relatedness using geographic information.

An important question in the the interpretation of the results concerns the definition of 'musical universal'. A strict definition of musical universal would mean that the feature is found in every piece of music, no matter its origin. @Savage2015-rp take a weaker definition of musical universal, defining it as a feature that occurs at least 50% of the time. Such features can be termed *statistical universals*.

The paper identifies a collection of statistical universals spanning different musical domains. The authors summarise them as follows:

> -   **Pitch**: Music tends to use discrete pitches (1) to form nonequidistant scales (2) containing seven or fewer scale degrees per octave (3). Music also tends to use descending or arched melodic contours (4) composed of small intervals (5) of less than 750 cents (i.e., a perfect fifth or smaller).
> -   **Rhythm**: Music tends to use an isochronous beat (6) organized according to metrical hierarchies (7) based on multiples of two or three beats (8)---especially multiples of two beats (9). This beat tends to be used to construct motivic patterns (10) based on fewer than five durational values (11).
> -   **Form**: Music tends to consist of short phrases (12) less than 9 s long.
> -   **Instrumentation**: Music tends to use both the voice (13) and (nonvocal) instruments (14), often together in the form of accompanied vocal song.
> -   **Performance style**: Music tends to use the chest voice (i.e., modal register) (15) to sing words (16), rather than vocables (nonlexical syllables).
> -   **Social context**: Music tends to be performed predominantly in groups (17) and by males (18). The bias toward male performance is true of singing, but even more so of instrumental performance.

Further to this analysis of individual features, @Savage2015-rp also studied the sense in which certain features tend to occur together. In particular, they find a collection of statistically associated features that seem to recur in the context of group performance and dance:

> -   Isochronous beat
> -   Motivic patterns
> -   Few durational values
> -   Phrase repetition
> -   Percussion instruments
> -   Syllabic singing

It is not hard to understand why the above features might be promoted in the context of dancing and group performance: each feature looks like it should be useful for encouraging inter-individual rhythmic entrainment. However, it is less obvious why some of the other musical features might become universal, for example discrete pitches or nonequidistant scales. We will revisit these questions in Chapter \@ref(origins-of-melodic-structures).

### Mehr et al. (2019)

More recently, a paper by @Mehr2019-wg includes a significant section on candidate musical universals. This follows a detailed analysis of the behavioural contexts of music around the world. This behavioural part of the paper is very impressive in its scope and quantitative execution; in contrast, unfortunately, the subsequent musical universals section feels a little disappointing, both for its lack of detail and for the Western-centric nature of its methods.

One proposed universal is tonality, specifically the notion that songs tend to be built around a particular tonal centre. This hypothesis is reasonable, but the analysis involves (a) having Western music theorists annotate tonal centres for the melodies, and (b) running the Krumhansl-Kessler keyfinding algorithm on the melodies, an algorithm which is trained on behavioural data from Western listeners. In both cases, one might expect the derived keys to be shaped significantly by the cultural expectations of Western listeners. A better approach to this question would define tonality in a much more culturally neutral way.

A second proposed universal is that melodies vary along two dimensions of complexity: one of which is melodic complexity, and the other of which is rhythmic complexity. These two dimensions are extracted through another principal component analysis. Again, the hypothesis seems reasonable, but the support from the data is relatively weak: the two components only explain 13.1% and 10.8% of the variance respectively. In other words, these two dimensions are only explaining a small part of the way in which melodic structure varies across the world.

A third proposed universal is that the prevalence of different melodic and rhythmic bigrams is distributed according to a so-called *power law*. Traditionally speaking, a bigram is a pair of elements from a given alphabet, for example 'AB' or 'CA'. The authors actually do not analyse bigrams in the conventional sense, which confuses things a little bit. Instead, they just look at frequency distributions for (a) melodic pitch intervals and (b) rhythmic ratios between successive notes. Curiously, the authors do not tabulate separate distributions for different cultures, but instead calculate an overall distribution of intervals and ratios across all the musical cultures in their sample. They find that certain intervals are particularly common cross-culturally (unison, major second, and minor third), and likewise certain rhythmic ratios (1:1, 2:1, and 3:1) are particularly common cross-culturally. Moreover, they show that, when ranking the full set of observed intervals/ratios, the distribution of their relative frequencies is well-approximated by a curve of a particular shape corresponding to a *power law*. Power-law shapes have previously been observed in many contexts, including music, language, and painting, but it would be interesting to see that this phenomenon replicates in different musical cultures. Unfortunately, the present analysis does not quite show this, because it doesn't compute separate distributions for individual cultures. However, it is arguably interesting nonetheless to know that we get a power-law distribution if we look at all the cultures jointly. It should be noted though that these distributions are filtered through the transcriptions of expert Western musicians, and may inherit some biases from them. In particular, the process of representing melodies on the Western 12-tone scale arguably forces the musicians to impose Western biases on their transcriptions; likewise, the rhythmic notation forces the musicians to express rhythms in terms of the integer-ratio rhythmic categories used in Western music theory. Future work ought to find ways to reduce these biases, perhaps by representing pitch and rhythm in a culturally neutral continuous space.

### Controversies

It should be noted that the concept of musical universals remain controversial. @Mehr2019-wg conducted a survey of 940 music scholars examining their perspective on this topic. Self-identified ethnomusicologists were particularly sceptical of the concept, with their free-text responses including the following:

> "I'm not sure precisely what the angle is here, but the question of musical universals has largely been settled by ethnomusicology--in short, there are very, very few of them. ... "

> "You cannot be serious. Universals? I understand and appreciate your project (really, human musicking is my intellectual jam). But you cannot suggest that scales are universal. You cannot suggest that tonality is universal. And why pitch organization? Because that's how European music culture thinks. ..."

> "The idea that music is universally understood is a long discounted theory. This line of questioning is condescending to 'people around the world'."

> "A study of universals would negate the rich diversity of the world's cultures. We are different, no matter how many similarities we may share. The value we must find lives in the in between spaces."

> "I fear that this undertaking, spearheaded by the paragon of colonialist expeditions (harvard grad students) risks recapitulating the efforts of comparative musicologists a century ago. Why identify universalities if not to compare and categorize? ..."

> "The idea that there is such a thing as musical universals (let alone that it should be studied) is deeply ethnocentric and Eurocentric. This idea reinforces 19th century European colonial ideology. There is no place for this type of antiquated and prejudiced thinking in a global 21st century education system marked by international and cultural diversity."

> "I prefer not to approach music in a universal way. Every culture perceives facts and music in a different way depending on their cultural background. Thus, I think that only people with similar cultural backgrounds could - or may - understand the music as well as the musical and non- musical behaviors of the people under research. "

> "The problem with the questions about whether this or that use of music is universal or not is that human societies are so many and so various! ..."

> "You are using the term 'music' in a very biased Western way. Frankly, I don't know what you mean by the term. You are treating it as a natural, objective thing that exists. ..."

They make important points, especially concerning the dangers of imposing an overly Western perspective on music studies. Nonetheless, there are many modern musicologists who now think that these statements go too far, and that we should not give up on the goal of developing a comparative understanding of the world's musics. It seems worthwhile to work towards a comparative musicology that acknowledges and rectifies the problematic cultural imperialism found in early work.

## Cultural contexts

An important principle in ethnomusicology is that we should pay serious attention to the social and cultural contexts within which music is produced. These sociocultural elements have most commonly been studied from qualitative perspectives such as ethnography, where the researcher spends a significant amount of time immersed in the relevant culture documenting events that they observe. This approach delivers very rich data with many personal insights. However, by itself it does not contribute directly to a comparative understanding of the world's musics, because no single researcher would have enough time to immerse themselves in a sufficient number of cultures to produce a proper global understanding of the world's musics.

The paper by @Mehr2019-wg addresses this problem by taking a large amount of ethnographic writings indexed in the [*eHRAF World Cultures Database*](https://ehrafworldcultures.yale.edu/ehrafe/), identifying passages related to vocal music, and constructing a large set of variables summarising key features of the writings, including both variables concerning the music itself (e.g. the sex of the singer, the presence of instruments) and variables concerning its behavioural context (e.g. the song appears to be part of a ceremony, or the song is associated with war). They christen the resulting dataset the *NHS Ethnography*, where 'NHS' stands for 'Natural History of Song'. The authors then construct various quantitative analyses that compare these variables across different musical cultures.

Quantitative analyses can quickly becoming overwhelming when they report many different variables at the same time. There are various strategies available for coping with this issue. One popular family of approaches is *dimensionality reduction*, where we try to summarise the collection of variables in terms of a small number of learned *dimensions*, where each dimension is shorthand for a collection of variables that tend to go together. There are several statistical approaches to dimensionality reduction out there, of which the most popular are *principal component analysis* and *factor analysis*. @Mehr2019-wg use a particular approach called Bayesian principal component analysis, a version of principal component analysis which is able to cope with the fact that the ethnographic dataset has missing data in certain places.

The Bayesian principal component analysis returns three main dimensions that together summarise much of the variation in behavioural context for the different songs in the NHS Ethnography. The authors describe these three dimensions as follows:

> -   **Formality**: "Excerpts high along this dimension describe ceremonial events involving adults, large audiences, and instruments; excerpts low on it describe informal events with small audiences and children."
> -   **Arousal**: "Excerpts high along this dimension describe lively events with many singers, large audiences, and dancing; excerpts low on it describe calmer events involving fewer people and less overt affect, such as people singing to themselves."
> -   **Religiosity**: "Passages high along this dimension describe shamanic ceremonies, possession, and funerary songs; passages low on it describe communal events without spiritual content, such as community celebrations."

One might hypothesise that music plays different roles in different cultures: for example, one culture might predominantly use music in a formal religious context, whereas other cultures might predominantly use music in an informal nonreligious context. The quantitative analyses show that there is indeed some cross-cultural variation along these lines. However, the takeaway message from the analyses is actually that there tends to be much more variation within a given culture than between different cultures. In other words, most cultures tend to exhibit multiple modes of music-making that explore different levels of formality, arousal, and religiosity; if we average over these different modes, we find that most cultures actually sit in a middleground for these three different variables.

In a subsequent analysis, the authors take a more granular approach to understanding music's behavioural contexts. They look in particular at a collection of keywords chosen to reflect hypotheses generated from published literature in anthropology, ethnomusicology, and cognitive science. They then look to see how often these keywords occur in the context of the musical parts of the ethnographies, as compared to non-musical parts.

They find indeed that, across different cultures, music tends to be associated in certain contexts above others. Many such contexts are listed in their Table 1, though some are more statistically prevalent than others. There seem to be particularly strong effects for the following contexts:

-   Dance
-   Healing
-   Religious activity, rituals
-   Mourning, death, funerals
-   Processions, spectacles, nuptials
-   Play, games, childhood activities
-   Love

The second part of the paper focuses on a secondary dataset of cross-cultural music recordings sampled to represent four different song categories chosen in previous work: dance songs, healing songs, love songs, and lullabies. This dataset is termed the *NHS Discography*.

In a first experiment, the authors demonstrate that Western (or at least Westernised) listeners are capable of categorising cross-cultural song recordings into these four different categories at a reasonable success rate, even though in most cases the listeners will have been totally unfamiliar with the source musical culture. Classification performance was largely independent of the listener's musical training, or indeed their self-reported familiarity with traditional music. This suggests that these song types tend to exhibit certain consistent musical features across different cultures that are associated with their particular functions, and that listeners are sensitive to the implications of these features even in the absence of relevant musical experience.

In a series of follow-up analyses, the authors explore what musical features might be responsible for distinguishing these different song functions. They find a variety of patterns here, including the following:

-   Dance and healing songs tend to have more differentiated accents than lullabies;
-   Dance songs tend to have fast tempos;
-   Love songs tend to have high variability in interval sizes;
-   Healing songs tend to have lots of stepwise motion.

The final part of the paper corresponds to candidate musical universals that are indepedent of particular behavioural contexts. See Section \@ref(structural-features-of-music) for a discussion of this section.

## Music cognition
