# Quantitative (I): Experiment design

## Experiments

Humans are natural experimenters. From a very young age, children naturally learn about the world through experimentation. Watching a young child play, you can just imagine the kinds of questions going through their heads: I wonder what sound it'll make if I hit this block on that pipe? I wonder what that bug tastes like? I wonder what will happen if I flush my toy car down the toilet?

These kinds of intuitive experiments are typically personal and *ad hoc*. You try something for yourself (e.g. eating a bug), you gain some kind of information (e.g. bugs taste gross), and you learn something for the future (don't eat bugs).

Science uses experiments to build up coherent theories about how the world works. It is fundamentally a *cumulative* endeavour: each scientist builds on the results generated by previous scientists.

> If I have seen further it is by standing on the shoulders of giants (Newton, 1676).

Experiments need certain qualities in order to be useful to future scientists. These qualities have gradually become canonised within the scientific value system, and are essential for work to be truly valued within the scientific community:

-   **Replicability.** When describing an experiment, we are obliged to present sufficient details such that another scientist can come along and repeat that same experiment. These details are essential for enabling other researchers to verify the *results* of the experiment by repeating it themselves. Such studies are termed *replication studies*, and are becoming an increasingly important and valued part of psychology research. These methodological details are also essential for enabling other researchers to verify the *conclusions* drawn from the experiment's results; it is often only when we investigate the details of the methodology that we end up spotting potential alternative explanations for a given pattern of results.

-   **Objectivity.** The intuitive experiments that a child performs to explore the world are naturally subjective; many of them rely after all on exploring the *sensations* delivered by objects (sound, taste, touch, ...). Subjective feelings are very valuable to the individual, but they are less meaningful to others, because different individuals by nature will have different subjective appraisals for a given physical phenomenon. Science therefore places high value on *objectivity*, the sense in which a piece of evidence is independent of the idiosyncrasies of the individual experimenter. Scientific measurements are therefore typically conducted using highly explicit methodologies, for example measuring length with a ruler, measuring voltage with a voltmeter, or assessing personality types with a questionnaire.

-   **Generalisability.** For an experiment to be relevant to other scientists, the experiment must be usefully *generalisable*. This can mean many things. For example, if we conduct a psychology experiment in the Centre for Music of Science, playing undergraduate participants' particular sounds and recording their responses, we might want to be convinced that we'd get analogous responses if we conducted the same experiment in the Department of Psychology at Goldsmiths using non-students recruited from the general London population. The more generalisable our results, the more convinced we can be that we've learned something general about human nature, rather than something specific about our particular experimental setup or our particular experiment group.

Designing an effective experiment that satisfies all of these principles while also telling us something useful is a challenging task, but it is also creative and rewarding. This chapter will go through this process step-by-step.

## Identifying a research topic

All experiments are situated within some kind of research topic. The research topic defines the body of knowledge to which we want to contribute, and typically has important implications for the methodologies that we will end up using. Here are some examples of research topics within the field of music psychology:

-   Music and dementia

-   Entrainment and social bonding

-   Expectation and musical pleasure

-   Memory for melodies

-   Timbre and synaesthesia

Sometimes you might dream up the research topic totally by yourself, for example when you apply for a PhD; other times you might be choosing between different predetermined research topics, for example as part of the research component of a university course, or when applying for postdoctoral researcher positions. In both scenarios, though, it is important to be able to critically evaluate different research topics and decide which possibilities work best for you. Let's go through a few different dimensions to think about:

### Impact

Impact can be defined as the sense in which a piece of research affects the world around it. Research can have impact in many ways, but it's often helpful to differentiate two kinds of impact:

1.  The sense in which the research improves our understanding of the world (*basic* research, also known as *fundamental* research);

2.  The sense in which the research solves practical problems in the real world (*applied* research). This can be achieved for example by developing a new technology that can be applied in non-research contexts, or by generating information that influences public or private policy.

Several factors contribute to determining your capacity to achieve impact within a given research topic. Some relate to the research topic itself; some relate to you as a researcher.

1.  Perhaps the topic itself has intrinsically high potential impact. Cancer research would be one such example; successful contributions in cancer research can have immensely high impact on cancer sufferers around the world.

2.  Perhaps the topic is understudied. This most commonly happens early on in the study of a topic, when there has not yet been sufficient time for many researchers to recognise its potential.

3.  Perhaps the topic matches your own skills particularly well. Different skillsets are useful for different research topics; this is particularly relevant in music psychology, where musical researchers will often have deep personal experience with a particular research topic. This personal experience can be useful in all kinds of ways, ranging from identifying good research questions to developing good hypotheses to recruiting suitable participants.

### Environment

It is essential to consider whether you have the right environment available for performing your work. There are two particularly important factors to consider:

-   **Academic input**. Will you have a supervisor? (If you are an undergraduate or postgraduate student, almost certainly) Does your supervisor have expertise in the planned research topic, and/or in the relevant methodologies for that research topic? Are there other people in the research group/department/faculty/institution who could also give you useful feedback on your work?

-   **Resources**. Does your planned research topic require special equipment, or large amounts of money (e.g. for funding travel to remote locations, or for recruiting participants)? If so, will this equipment/money be available from your group/department/faculty/institution? If not, are there relevant grants you can apply to (e.g. from your college/university/national funding body) that could support the work?

### Personal interest

There's no escaping the fact that different people find different things interesting. I might be biased, but I think that music psychology is a particularly rich field in this respect, because it contains so many research topics that music enthusiasts can connect to in a deep and personal sense. There is no shame in studying film music because you have a particular interest in listening to film music, or in studying music and dementia because you have a relative with dementia.

### Personal development

Most research projects offer opportunities for knowledge and skill development. By working in a field, you will necessarily have to learn a lot about the relevant literature, and become something of an expert in the particular topic that you are studying. It's worth taking some time to consider which research topics you would find most rewarding to learn so much about. Conducting scientific experiments moreover gives an opportunity to develop many practical skills, such as interviewing, survey design, programming, or data analysis; it's worth considering which of these potential skills would be most valuable to you to learn, either because you think you would enjoy learning them, or because you think they would serve you well in the future.

Learning new skills is good, but it is also time-consuming. Generally you should choose topics that provide some balance between the familiar and unfamiliar; the unfamiliar aspects are useful learning opportunities, but the familiar aspects help you to work efficiently and effectively.

### Cost-benefit trade-off

Lastly, it is important to evaluate the potential costs involved in the proposed research direction, and determine how they compare to the potential impact of the work. This becomes particularly relevant in the latter stages of planning process, but we'll discuss this issue here anyway for completeness.

The most obvious kind of costs are *financial* costs: some research simply costs a lot of money. There are however several other kinds of costs which are often underappreciated in the project planning stage.

-   **Time.** It is important to consider time both in terms of wall-clock hours (i.e. how much time elapses before the start and end of a project) and in terms of person hours (i.e. how many hours the researchers need to spend actively working on the project). Wall-clock hours become increasingly important for research projects with short time windows and strict deadlines, for example undergraduate or masters' projects.

-   **Ethics.** Certain projects bring personal costs, or risks of costs, to the participants. For example, a trial medical drug could harm participants through unknown side effects, or a survey about taboo behaviours could harm its participants if their anonymity were compromised. The research should only be undertaken if the likely benefits of the research outweigh the likely costs, and then only if the participants provide informed consent. All psychological research projects (even undergraduate projects) should generally go to an institutional ethics board for approval before the research is conducted.

### Idea generation

It is one thing to appraise a given research topic along these different dimensions, but how do we identify candidate research topics in the first place? This is fundamentally a personal process, and so it's difficult to prescribe a universal strategy here. Nonetheless, there are a couple of useful things worth considering:

-   **Reading broadly.** Most fields have a fair few high-level books that lay out the many research topics that make up the field. In music psychology, good examples would be the *Psychology of Music* [@Deutsch2013-xv], the *Oxford Handbook of Music Psychology* [@Hallam2017-xk], or *The Science and Psychology of Music* [@Thompson2021-eu]*.*

-   **Attending talks and conferences.** Listening to other people present their work is a great way to foster your own ideas. Most academic institutions hold regular seminar series concerning various research fields or topics, which typically include a mixture of internal and external speakers. In addition to this, particular research fields tend to hold regular national or international conferences, where researchers congregate to share and discuss their latest research. Attending one of these conferences (or workshops, which are essentially informal versions of conferences) can be a great way to be exposed to research topics and methodologies you had never really considered before, as well as meeting other interesting people in the field. Conferences can be expensive to attend in person, but many offer special discounts or funding to students. Moreover, if you can't attend in person, it is nowadays often possible to watch recordings of the talks afterwards on YouTube, or at least to read the conference's 'proceedings' book which compiles summaries of the research projects that were presented.

## Identifying a research question

What is a research question?

While research topics are relatively long-lived, research questions have a shorter timespan. Ideally, each study identifies an important unsolved research question, then conducts experiments to find the anwer to that research question. The field gradually moves forward by successively answering research questions. Of course, it's difficult to get a definitive answer in any one study, and sometimes the field gets stuck on particular research questions for a long time!

-   Literature reviews

    -   Ad hoc review

    -   Systematic literature review

## Identifying an appropriate methodology

### Qualitative versus quantitative research

### Relevant quantitative methodologies for music psychology

#### Psychological studies

#### Corpus studies

#### Acoustic studies

## Further reading

-   Chapter 1, 'Research questions' in @Williamon2021-ld ([eBook link](https://ezp.lib.cam.ac.uk/login?url=http://dx.doi.org/10.1093/oso/9780198714545.001.0001)).
