# (PART) Methods {.unnumbered}

# Introduction

Humans are natural experimenters. From a very young age, children naturally learn about the world through experimentation. Watching a young child play, you can just imagine the kinds of questions going through their heads: I wonder what sound it'll make if I hit this block on that pipe? I wonder what that bug tastes like? I wonder what will happen if I flush my toy car down the toilet?

These kinds of intuitive experiments are typically personal and *ad hoc*. You try something for yourself (e.g. eating a bug), you gain some kind of information (e.g. bugs taste gross), and you learn something for the future (don't eat bugs).

Science uses experiments to build up coherent theories about how the world works. It is fundamentally a *cumulative* endeavour: each scientist builds on the results generated by previous scientists.

> If I have seen further it is by standing on the shoulders of giants (Newton, 1676).

Experiments need certain qualities in order to be useful to future scientists. These qualities have gradually become canonised within the scientific value system, and are essential for work to be truly valued within the scientific community:

-   **Replicability.** When describing an experiment, we are obliged to present sufficient details such that another scientist can come along and repeat that same experiment. These details are essential for enabling other researchers to verify the *results* of the experiment by repeating it themselves. Such studies are termed *replication studies*, and are becoming an increasingly important and valued part of psychology research. These methodological details are also essential for enabling other researchers to verify the *conclusions* drawn from the experiment's results; it is often only when we investigate the details of the methodology that we end up spotting potential alternative explanations for a given pattern of results.

-   **Objectivity.** The intuitive experiments that a child performs to explore the world are naturally subjective; many of them rely after all on exploring the *sensations* delivered by objects (sound, taste, touch, ...). Subjective feelings are very valuable to the individual, but they are less meaningful to others, because different individuals by nature will have different subjective appraisals for a given physical phenomenon. Science therefore places high value on *objectivity*, the sense in which a piece of evidence is independent of the idiosyncrasies of the individual experimenter. Scientific measurements are therefore typically conducted using highly explicit methodologies, for example measuring length with a ruler, measuring voltage with a voltmeter, or assessing personality types with a questionnaire.

-   **Generalisability.** For an experiment to be relevant to other scientists, the experiment must be usefully *generalisable*. This can mean many things. For example, if we conduct a psychology experiment in the Centre for Music of Science, playing undergraduate participants' particular sounds and recording their responses, we might want to be convinced that we'd get analogous responses if we conducted the same experiment in the Department of Psychology at Goldsmiths using non-students recruited from the general London population. The more generalisable our results, the more convinced we can be that we've learned something general about human nature, rather than something specific about our particular experimental setup or our particular experiment group.

Designing an effective experiment that satisfies all of these principles while also telling us something useful is a challenging task, but it is also creative and rewarding. This chapter will go through this process step-by-step.
