# Quantitative vs. qualitative

It is useful to differentiate two main traditions of empirical research: *quantitative* research and *qualitative* research. Traditionally speaking, these two research traditions have often behaved as opposing camps, with individual researchers aligning themselves one way and barely recognising work carried out the other way. However, it is nowadays not uncommon for music psychology researchers to sit between the two camps, incorporating elements of both quantitative and qualitative research into the same research programme and even into the same study.

Quantitative research is identified by a particular emphasis on objectivity and generalisability.

-   Subjectivity is minimised through the application of highly codified data collection processes, which in the context of psychology means for example administering closed-form questionnaires (where participants might answer questions by selecting numbers on a scale from 1 to 7) or behavioural tasks implemented on computers (where participants might be presented with various stimuli and respond using a keyboard and mouse). Most commonly the results from such studies will be represented numerically, for example as scores from different subscales of a questionnaire, or as reaction times from a perceptual task.

-   Generalisability is pursued by favouring experiments using large participant groups sampled from a well-defined population, and by using so-called *inferential* statistical methods to estimate the confidence with which the results from a given experiment can be generalised to future experiments. These methods tie closely with the methods used in non-human sciences, for example physics and chemistry.

The objectivity and generalisability of quantitative research comes at a cost. Quantitative data collection processes typically provide only a very restricted window onto an individual's experience at a particular point in time; this is a result both of the drive for objectivity (which mandates highly codified and inflexible data collection procedures) and of the drive for generalisability (which mandates large participant groups, which in turn require relatively standardised and automated data collection procedures). A necessary consequence is that quantitative studies are generally limited to testing rather specific research questions or hypotheses. The researcher is therefore limited to finding things that they were already looking for, and that introduces its own kind of subjectivity and bias into the scientific process. A particular risk is that the researcher ends up assuming a theoretical framework that imposes values or assumptions derived perhaps from their own cultural or socioeconomic background that are fundamentally inconsistent with the underlying experience of the people being studied.

Qualitative research methods seek to address these concerns.
