on:
  push:
     branches:
       - main

name: renderbook

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Setup renv
        run: Rscript -e 'install.packages("renv"); renv::restore()'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@main
     - name: Download artifact
       uses: actions/download-artifact@v4
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: pmcharrison/GitHub-Pages-deploy@v3
       with:
         email: ${{ secrets.EMAIL }}
         build_dir: _book
       env:            # must be a verified email
         GITHUB_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
    
 
